/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_EXAMPLES_SIMPLE_WEIGHTSBIASES_PB_H_INCLUDED
#define PB_EXAMPLES_SIMPLE_WEIGHTSBIASES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _WeightsBiases {
    pb_callback_t w1;
    pb_callback_t b1;
    pb_callback_t w2;
    pb_callback_t b2;
} WeightsBiases;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WeightsBiases_init_default               {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define WeightsBiases_init_zero                  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define WeightsBiases_w1_tag                     1
#define WeightsBiases_b1_tag                     2
#define WeightsBiases_w2_tag                     3
#define WeightsBiases_b2_tag                     4

/* Struct field encoding specification for nanopb */
#define WeightsBiases_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    w1,                1) \
X(a, CALLBACK, REPEATED, FLOAT,    b1,                2) \
X(a, CALLBACK, REPEATED, FLOAT,    w2,                3) \
X(a, CALLBACK, REPEATED, FLOAT,    b2,                4)
#define WeightsBiases_CALLBACK pb_default_field_callback
#define WeightsBiases_DEFAULT NULL

extern const pb_msgdesc_t WeightsBiases_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WeightsBiases_fields &WeightsBiases_msg

/* Maximum encoded size of messages (where known) */
/* WeightsBiases_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
